services:
    _defaults:
        autowire: true
        autoconfigure: true

    Bnix\PimcorePrestashopBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Enum/'

    _instanceof:
        Bnix\PimcorePrestashopBundle\Mapping\FieldMapperInterface:
            tags:
                - 'bnix.pimcore_prestashop.field_mapper'